POST http://127.0.0.1:8000/api/project/project_delete/
Content-Type: application/json

{
    "params": [
        {
          "username": "ai_app",
          "token": "evb41xz0rrepmv0g1nx1z2upjab9w28d",
          "user_id": "8"
        }
      ],
  "id": "24"
}

###
POST http://127.0.0.1:8000/api/project/project_create_or_update/
Content-Type: application/json

{
  "params": [
        {
          "username": "ai_app",
          "token": "ojvuew8x07ux7fsfz3l0wlp7km3biblq",
          "user_id": "8"
        }
      ],
  "data": [
    {
      "id": "4",
      "project_name": "fish",
      "object_detection_model_name": "19"
    },
    {
      "id": "5",
      "project_name": "MRI",
      "object_detection_model_name": "19"
    }
  ]
}





###
GET http://127.0.0.1:8000/api/object_detection_model/object_detection_model_list/?user_id=8&username=ai_app
Accept: application/json

###
GET http://127.0.0.1:8000/api/project/project_list/?model_name=EfficientDet&id=19&user_id=8&username=ai_app
Accept: application/json


//{
//  "params": [
//        {
//          "username": "ai_app",
//          "token": "90h3csnejam5wlem2sqle6c1wzldd49y",
//          "user_id": "8"
//        }
//      ],
//  "data": [
//    {
//      "id": "0",
//      "project_name": "test",
//      "object_detection_model_name_id": "19"
//    }
//  ]
//}


###
POST http://127.0.0.1:8000/api/login
Content-Type: application/json

{
  "username": "ai_app",
  "password": "Ai-app123dev"
}

###
POST http://localhost:8000/api/incomeforecast/income_forecast_update/
Content-Type: application/json

{
    "income_forecast_id": "8e8d922c-0cf0-fbb8-68be-ce17e5737c4f",
    "data": [
        {
            "income_forecast_id": "8e8d922c-0cf0-fbb8-68be-ce17e5737c4f",
            "payment_date": "2022-04-25",
            "age": "28",
            "industry": "システム開発",
            "classification": "給料",
            "total_amount": "240000",
            "deduction_amount": "68000",
            "take_home_amount": "200600",
            "profile": "b1639e6e-afe1-4b4f-aaf2-09966c663b0e"
        }
    ]
}

###
POST http://localhost:8000/api/incomeforecast/income_forecast_update/
Content-Type: application/json
# 更新

//{
//    "income_forecast_id": "",
//    "data": [
//        {
//            "payment_date": "2022-08-25",
//            "age": "28",
//            "industry": "システム開発",
//            "classification": "給料",
//            "total_amount": "240000",
//            "deduction_amount": "39400",
//            "income_forecast_id": "",
//            "profile": "b1639e6e-afe1-4b4f-aaf2-09966c663b0e",
//            "take_home_amount": "200600"
//        }
//    ]
//}

{
    "user_id": "5",
    "data": [
        {
            "income_forecast_id": "16ce7f02-6399-4915-b9f7-7308248f439b",
            "payment_date": "2022-06-15",
            "age": "32",
            "industry": "test",
            "classification": "賞与",
            "total_amount": "2500000",
            "deduction_amount": "450000",
            "take_home_amount": "2050000"
        }
    ]
}



###
POST http://localhost:8000/api/incomeforecast/income_forecast_update/
Content-Type: application/json
# 新規登録

//{
//    "income_forecast_id": "",
//    "data": [
//        {
//            "payment_date": "2022-08-25",
//            "age": "28",
//            "industry": "システム開発",
//            "classification": "給料",
//            "total_amount": "240000",
//            "deduction_amount": "39400",
//            "income_forecast_id": "",
//            "profile": "b1639e6e-afe1-4b4f-aaf2-09966c663b0e",
//            "take_home_amount": "200600"
//        }
//    ]
//}

{
    "user_id": "5",
    "data": [
        {
            "payment_date": "2022-06-15",
            "age": "30",
            "industry": "ppp",
            "classification": "給料",
            "total_amount": "250000",
            "deduction_amount": "45000",
            "take_home_amount": "205000"
        }
    ]
}



###
POST http://127.0.0.1:8000/api/income/income_update/
Content-Type: application/json

{
    "income_id": "",
    "data": [
        {
            "company_name": "",
            "company_size": "",
            "industry": "システム開発",
            "employee_number": "25",
            "avg_age": 22,
            "avg_income": ""
        }
    ]
}

###
POST http://127.0.0.1:8000/api/income/income_update/
Content-Type: application/json

{
    "income_id": "",
    "data": [
        {
            "company_name": "PayPay株式会社",
            "company_size": "ベンチャー",
            "industry": "モバイルペイメント等電子決済サービスの開発・提供",
            "employee_number": "1600",
            "avg_age": "36",
            "avg_income": "637"
        }
    ]
}

###
POST http://127.0.0.1:8000/api/income/income_update/
Content-Type: application/json

{
    "income_id": "6df9e529-c71e-8b41-cfa3-cf8ccdefb589",
    "data": [
        {
            "income_id": "6df9e529-c71e-8b41-cfa3-cf8ccdefb589",
            "company_name": "株式会社キーエンス",
            "company_size": "大企業",
            "industry": "電気機器",
            "employee_number": "8380",
            "avg_age": "42",
            "avg_income": "1839"
        }
    ]
}

