# Generated by Django 4.1.7 on 2023-03-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ObjectDetectionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_detection_model_name",
                    models.CharField(max_length=20, unique=True),
                ),
                ("delete_flag", models.IntegerField()),
                ("update_user", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField()),
            ],
        ),
    ]
